# Generated by Django 3.2.9 on 2021-11-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, max_length=14, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
